GET http://localhost:8080/api/time/15/2022-07-13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSkMiLCJpYXQiOjE2NTc4MTIxMTV9.hCCZWHfmr4HfGt-KxRHbQAi_QQ7fGaNHEleX3a5tFYM

###

DELETE http://localhost:9090/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSkMiLCJpYXQiOjE2NTc4MTIxMTV9.Yo_GeP3682o3c_NOZCvOHnQReXh29MvjIbg5msbXFvc"
}

###

POST http://localhost:9090/refreshtoken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSkMiLCJpYXQiOjE2NTc4MTIxMTV9.Yo_GeP3682o3c_NOZCvOHnQReXh29MvjIbg5msbXFvc"
}

###

POST http://localhost:9090/login
Content-Type: application/json

{
  "username": "JC"
}