GET http://localhost:8080/api/time/15/2022-07-13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU3Nzg3OTI3LCJleHAiOjE2NTc3ODc5NTd9.RSE-LED_JBSLs0ZgWv4w_WJ9m1cTbPy5_veRRi5BkxQ

###

DELETE http://localhost:9090/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU3Nzg3MjgxLCJleHAiOjE2NTc3ODczMTF9.ADIflUhy13jYmr8quEpR66AS2-ERrJa3fBj8I458lnI"
}

###

POST http://localhost:9090/refreshtoken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjU3Nzg3ODgyfQ.UwlP-6dtfyw7wwAnlXCrS-39-JU22qzt-R_gJH19Ihw"
}

###

POST http://localhost:9090/login
Content-Type: application/json

{
  "username": "Jim"
}